### ISSUE TITLE
Removing extension assets then cancel leaves ghost assets

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#214] opened 2018-01-24 15:32 UTC
Add an extension asset to a component (e.g. audio) click save. Then edit again and remove, this time click cancel.

Assets remains in component JSOn but is removed from courseassets collection. results in missing file in download.

Direct component assets are OK.
Also not able to reproduce in OS AT 0.4.1 RC2. Re-test after upgrading to latest OS AT.

**Comment by deltanetdan** [comment] 2021-09-30 08:17
duplicate of #137

**Closed as completed by deltanetdan** 2021-09-30 08:17 UTC
Labels: bug, OS
